DisablePathCorrection: false
EnablePathEscape: false
FireMethodNotAllowed: false
DisableBodyConsumptionOnUnmarshal: false
DisableAutoFireStatusCode: false
TimeFormat: Mon,02 Jan 2006 15:04:05 GMT
Charset: utf-8